export const QUERY_PERMISSION = 'QUERY_PERMISSION';
export const QUERY_LIST_NEWS = 'QUERY_LIST_NEWS';
export const QUERY_NEWS_DETAIL = 'QUERY_NEWS_DETAIL';

export const QUERY_LIST_RECRUITMENT = 'QUERY_LIST_RECRUITMENT';
export const QUERY_RECRUITMENT_DETAIL = 'QUERY_RECRUITMENT_DETAIL';

export const QUERY_LIST_FAQ = 'QUERY_LIST_FAQ';
export const QUERY_FAQ_DETAIL = 'QUERY_FAQ_DETAIL';

export const QUERY_LIST_DOCUMENT = 'QUERY_LIST_DOCUMENT';
export const QUERY_DOCUMENT_DETAIL = 'QUERY_DOCUMENT_DETAIL';

export const QUERY_LIST_SURVEY = 'QUERY_LIST_SURVEY';
export const QUERY_SURVEY_DETAIL = 'QUERY_SURVEY_DETAIL';

export const QUERY_LIST_USER = 'QUERY_LIST_USER';
export const QUERY_USER_DETAIL = 'QUERY_USER_DETAIL';

export const QUERY_LIST_ADMIN = 'QUERY_LIST_ADMIN';
export const QUERY_ADMIN_DETAIL = 'QUERY_ADMIN_DETAIL';

export const QUERY_LIST_ROLE = 'QUERY_LIST_ROLE';
export const QUERY_DETAIL_ROLE = 'QUERY_DETAIL_ROLE';

export const QUERY_LIST_TRAINER = 'QUERY_LIST_TRAINER';
export const QUERY_TRAINER_DETAIL = 'QUERY_TRAINER_DETAIL';

// constant

export const typeForgotPassword = {
  administrator: 'administrator',
  customer: 'customer',
  trainer: 'trainer',
};
