export const ADMIN = '/admin';
export const PARTNER = '/partner';

const ACTION = {
  CREATE: 'create',
  DETAIL: 'detail',
};

export const ADMIN_ROUTE_NAME = {
  DASHBOARD: 'admin',
  SIGNIN: 'signin',
  FORGOT_PASSWORD: 'forgot-password',
  ROLE_MANAGEMENT: 'role-management',
  USER_MANAGEMENT: 'user-management',
  ADMIN_MANAGEMENT: 'admin-management',
  CHART_MANAGEMENT: 'chart-management',
  COLOR_MANAGEMENT: 'color-management',
  CATEGORY_MANAGEMENT: 'category-management',
  SIZE_MANAGEMENT: 'size-management',
  PRODUCT_MANAGEMENT: 'product-management',
  ORDER_MANAGEMENT: 'order-management',
  BANNER_MANAGEMENT: 'banner-management',

  PROFILE: 'profile',

  CREATE: 'create',
  DETAIL: 'detail',
};

export const ADMIN_ROUTE_PATH = {
  DASHBOARD: `/${ADMIN_ROUTE_NAME.DASHBOARD}`,
  SIGNIN: `${ADMIN}/${ADMIN_ROUTE_NAME.SIGNIN}`,
  FORGOT_PASSWORD: `${ADMIN}/${ADMIN_ROUTE_NAME.FORGOT_PASSWORD}`,

  ROLE_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.ROLE_MANAGEMENT}`,
  CREATE_ROLE: `${ADMIN}/${ADMIN_ROUTE_NAME.ROLE_MANAGEMENT}/${ACTION.CREATE}`,
  DETAIL_ROLE: `${ADMIN}/${ADMIN_ROUTE_NAME.ROLE_MANAGEMENT}/${ACTION.DETAIL}`,

  USER_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.USER_MANAGEMENT}`,
  CREATE_USER: `${ADMIN}/${ADMIN_ROUTE_NAME.USER_MANAGEMENT}/${ACTION.CREATE}`,

  ADMIN_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.ADMIN_MANAGEMENT}`,
  CREATE_ADMIN: `${ADMIN}/${ADMIN_ROUTE_NAME.ADMIN_MANAGEMENT}/${ACTION.CREATE}`,
  CHART_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.CHART_MANAGEMENT}`,

  COLOR_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.COLOR_MANAGEMENT}`,
  CREATE_COLOR: `${ADMIN}/${ADMIN_ROUTE_NAME.COLOR_MANAGEMENT}/${ACTION.CREATE}`,

  SIZE_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.SIZE_MANAGEMENT}`,
  CREATE_SIZE: `${ADMIN}/${ADMIN_ROUTE_NAME.SIZE_MANAGEMENT}/${ACTION.CREATE}`,

  CATEGORY_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.CATEGORY_MANAGEMENT}`,
  CREATE_CATEGORY: `${ADMIN}/${ADMIN_ROUTE_NAME.CATEGORY_MANAGEMENT}/${ACTION.CREATE}`,

  PRODUCT_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.PRODUCT_MANAGEMENT}`,
  CREATE_PRODUCT: `${ADMIN}/${ADMIN_ROUTE_NAME.PRODUCT_MANAGEMENT}/${ACTION.CREATE}`,

  ORDER_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.ORDER_MANAGEMENT}`,
  UPDATE_ORDER: `${ADMIN}/${ADMIN_ROUTE_NAME.ORDER_MANAGEMENT}/${ACTION.DETAIL}/:id`,

  BANNER_MANAGEMENT: `${ADMIN}/${ADMIN_ROUTE_NAME.BANNER_MANAGEMENT}`,

  PROFILE: `${ADMIN}/${ADMIN_ROUTE_NAME.PROFILE}`,
};

export const PARTNER_ROUTE_NAME = {
  DASHBOARD: '/',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  USER_MANAGEMENT: '/user-management',
  VOUCER_MANAGEMENT: '/voucher-management',
  STORE_MANAGEMENT: '/store-management',
  STORE_MANAGEMENT_CREATE: `/store-management/create`,
  STORE_MANAGEMENT_DETAIL: `/store-management/:id`,
  VOUCHER_MANAGEMENT_CREATE: `/voucher-management/create`,
  VOUCHER_MANAGEMENT_DETAIL: `/voucher-management/:id`,
  VOUCHER_MANAGEMENT_ACTIVE: `/voucher-management/active`,
  VOUCHER_MANAGEMENT_HISTORY: `/voucher-management/histories`,
  STATISTICAL_MANAGEMEN: `/statistical-management`,

  PROFILE: '/profile',

  CREATE: '/create',
  DETAIL: '/detail',
};

export const PARTNER_ROUTE_PATH = {
  DASHBOARD: `${PARTNER}${PARTNER_ROUTE_NAME.DASHBOARD}`,
  SIGNIN: `${PARTNER}${PARTNER_ROUTE_NAME.SIGNIN}`,
  SIGNUP: `${PARTNER}${PARTNER_ROUTE_NAME.SIGNUP}`,
  FORGOT_PASSWORD: `${PARTNER}${PARTNER_ROUTE_NAME.FORGOT_PASSWORD}`,
  USER_MANAGEMENT: `${PARTNER}${PARTNER_ROUTE_NAME.USER_MANAGEMENT}`,
  STORE_MANAGEMENT: `${PARTNER}${PARTNER_ROUTE_NAME.STORE_MANAGEMENT}`,
  STORE_MANAGEMENT_CREATE: `${PARTNER}${PARTNER_ROUTE_NAME.STORE_MANAGEMENT_CREATE}`,
  STORE_MANAGEMENT_DETAIL: `${PARTNER}${PARTNER_ROUTE_NAME.STORE_MANAGEMENT_DETAIL}`,

  VOUCER_MANAGEMENT: `${PARTNER}${PARTNER_ROUTE_NAME.VOUCER_MANAGEMENT}`,
  VOUCHER_MANAGEMENT_CREATE: `${PARTNER}${PARTNER_ROUTE_NAME.VOUCHER_MANAGEMENT_CREATE}`,
  VOUCHER_MANAGEMENT_DETAIL: `${PARTNER}${PARTNER_ROUTE_NAME.VOUCHER_MANAGEMENT_DETAIL}`,
  VOUCHER_MANAGEMENT_ACTIVE: `${PARTNER}${PARTNER_ROUTE_NAME.VOUCHER_MANAGEMENT_ACTIVE}`,
  VOUCHER_MANAGEMENT_HISTORY: `${PARTNER}${PARTNER_ROUTE_NAME.VOUCHER_MANAGEMENT_HISTORY}`,
  STATISTICAL_MANAGEMEN: `${PARTNER}${PARTNER_ROUTE_NAME.STATISTICAL_MANAGEMEN}`,

  PROFILE: `${PARTNER}${PARTNER_ROUTE_NAME.PROFILE}`,
};
